-- deepseek 协助编写，获取文件名
local function get_file_path()
  local file_path = vim.api.nvim_eval("expand('%:p')")
  local buf = vim.api.nvim_create_buf(false, true) -- 非列表 buffer，可编辑

  -- 将 buffer 显示在一个新的窗口中
  vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    width = 60,
    height = 1,
    row = 1,
    col = 1,
    style = "minimal",
    border = "single",
  })

  vim.api.nvim_buf_set_lines(buf, 0, -1, false, { file_path })
end

vim.api.nvim_create_user_command("GetFilePath", get_file_path, {})

vim.api.nvim_create_user_command("InsertUUID", function()
  local function generate_uuid()
    local template = "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx"
    return string.gsub(template, "[xy]", function(c)
      local v = (c == "x") and math.random(0, 15) or math.random(8, 11)
      return string.format("%x", v)
    end)
  end

  math.randomseed(os.time()) -- Seed the random number generator
  local uuid = generate_uuid()
  local formatted_uuid = "<!-- " .. uuid .. " -->"
  vim.api.nvim_put({ formatted_uuid }, "", false, true)
end, { desc = "insert a generated UUID as an HTML comment" })

-- generated by Qwen
local function close_hidden_buffers()
  local current_buf = vim.api.nvim_get_current_buf()

  local tabpages = vim.api.nvim_list_tabpages()
  local visible_buffers = {}

  for _, tab in ipairs(tabpages) do
    local wins = vim.api.nvim_tabpage_list_wins(tab)
    for _, win in ipairs(wins) do
      local buf = vim.api.nvim_win_get_buf(win)
      visible_buffers[buf] = true
    end
  end

  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    if buf == current_buf then
      goto skip
    end

    if visible_buffers[buf] then
      goto skip
    end

    if vim.api.nvim_get_option_value("buftype", { buf = buf }) == "terminal" then
      vim.notify("Buffer " .. buf .. " is a terminal, not closing", vim.log.levels.INFO)
      goto skip
    end

    if vim.api.nvim_get_option_value("modified", { buf = buf }) then
      vim.notify("Buffer " .. buf .. " is modified, not closing", vim.log.levels.WARN)
      goto skip
    end

    vim.api.nvim_buf_delete(buf, { force = false })

    ::skip::
  end
end

vim.keymap.set(
  "n",
  "<space>bc",
  close_hidden_buffers,
  { noremap = true, silent = true, desc = "close all hidden buffers" }
)

-- 拷贝， <leader> a ，然后粘贴
-- 将 clipboard 中的 gdb backtrace 简化之后再粘贴出来
-- 传入 input 时直接处理字符串并返回结果，不读写剪贴板（方便测试）。
function ProcessClipboard(input)
  local clipboard_content
  if input then
    clipboard_content = input
  else
    -- SSH/tmux 下读取本地系统剪贴板不一定可用；provider 失败时给出明确提示。
    local ok, content = pcall(vim.fn.getreg, "+")
    if not ok then
      vim.notify(
        "Failed to read + register from clipboard provider. Paste the text into a buffer first, then process it there.",
        vim.log.levels.ERROR
      )
      return
    end
    clipboard_content = content
  end

  -- 检查剪贴板内容是否为空
  if clipboard_content == "" then
    print("Clipboard is empty!")
    return
  end

  -- 1. 合并所有行，再按 #数字 重新分割，处理 gdb backtrace 的折行
  local joined = clipboard_content:gsub("\n", " ")
  local frames = {}
  for frame in joined:gmatch("#%d+%s*([^#]*)") do
    -- 2. 去掉 "0xffffffff812e6b58 in " 这类地址前缀
    frame = frame:gsub("^%s*0x%x+%s*in%s*", "")
    -- 3. 去掉前导空格
    frame = frame:gsub("^%s*", "")
    -- 4. 提取函数名，遇到 ( 为止
    frame = frame:match("^[^%(]+")
    if frame then
      frame = frame:gsub("%s*$", "")
      if frame ~= "" then
        table.insert(frames, frame)
      end
    end
  end

  if #frames == 0 then
    print("No gdb backtrace frames found in clipboard.")
    return
  end

  -- 5. 反转调用栈，并生成缩进列表
  local indent = "- "
  local result = {}
  for i = #frames, 1, -1 do
    table.insert(result, indent .. frames[i])
    indent = "  " .. indent
  end

  local output = table.concat(result, "\n")

  if input then
    return output
  end

  vim.fn.setreg("+", output)
  print(output)
  print("trim finished !")
end

-- 映射快捷键
vim.keymap.set("n", "<leader>a", ProcessClipboard, { silent = true })
