
FROM archlinux 
# create a user

# zsh

# spacevim clone

# 你的 user name

# 如何自动切换到 user
  244  anzhuang user-manager
  250  useradd -m -G wheel -s /bin/bash shen
# 或者使用这种方法，全部默认
  user -m shen 

anzhuang fakeroot
anzhuang sudo
anzhuang fzf

# 默认切换到 user

https://unix.stackexchange.com/questions/9714/what-is-the-need-for-fakeroot-command-in-linux
# yay

   21  anzhuang lsd
   22  anzhuang lazygit
   24  anzhuang node
   25  anzhuang ccls
   28  anzhuang curl
   46  anzhuang nodejs
   47  anzhuang yarn
   51  anzhuang ping
   81  anzhuang npm
   93  anzhuang pip
   94  anzhuang pip3
   96  anzhuang gem
  119  anzhuang python-pip
  131  anzhuang bear
  138  anzhuang make
  142  anzhuang flex
  144  anzhuang bison
  145  anzhuang textstyle
  146  anzhuang xmlto kmod inetutils bc libelf git
  148  anzhuang gettext
  182  anzhuang cmake
  195  anzhuang coreutils
  206  anzhuang htop
  216  anzhuang ctags
  225  anzhuang autojump
  244  anzhuang user-manager
  330  anzhuang ripgrep
  390  anzhuang libaio
  404  anzhuang libaio
  416  anzhuang cppman
  542  anzhuang xclip
  610  anzhuang code
  629  anzhuang bash-language-server
  638  anzhuang gnuplot
  667  anzhuang man
  669  anzhuang mkfs
  670  anzhuang mkfs.ext4
  676  anzhuang frpc
  700  anzhuang ripgrep
  701  anzhuang the_silver_searcher
  713  anzhuang pkg-config
  715  anzhuang pod2man
  
