# TODO
# fzf version >= 0.22
sudo apt install fd-find

# https://github.com/koalaman/shellcheck
sudo apt install shellcheck
# https://github.com/mvdan/sh
GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
# https://github.com/languagetool-org/languagetool
curl -L https://raw.githubusercontent.com/languagetool-org/languagetool/master/install.sh | sudo bash <options>

# 视频下载
# https://github.com/soimort/you-get
pip3 install you-get

# https://github.com/sharkdp/bat/issues/938
sudo apt install -o Dpkg::Options::="--force-overwrite" bat ripgrep

# install docker on ubuntu
# https://docs.docker.com/engine/install/ubuntu/

# 设置默认 terminal
# https://askubuntu.com/questions/1157503/deepin-terminal-not-showing-up-in-x-terminal-emulator-list
sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator ~/.local/bin/alacritty 50

# Select your terminal
sudo update-alternatives --config x-terminal-emulator
