# TODO
# fzf version >= 0.22
sudo apt install fd-find

# 视频下载
# https://github.com/soimort/you-get
pip3 install you-get

# https://github.com/sharkdp/bat/issues/938
sudo apt install -o Dpkg::Options::="--force-overwrite" bat ripgrep

# install docker on ubuntu
# https://docs.docker.com/engine/install/ubuntu/

# 设置默认 terminal
# https://askubuntu.com/questions/1157503/deepin-terminal-not-showing-up-in-x-terminal-emulator-list
sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator ~/.local/bin/alacritty 50

# Select your terminal
sudo update-alternatives --config x-terminal-emulator
