# generated by gemini
{
  pkgs ? import <nixpkgs> { },
}:

let
  pythonEnv = pkgs.python3.withPackages (
    ps: with ps; [
      argcomplete
      requests
      setuptools # 常常需要用来构建或安装
    ]
  );
in
pkgs.mkShell {
  name = "virtme-ng-dev";

  nativeBuildInputs = with pkgs; [
    # Python environment with dependencies
    pythonEnv
    uv

    # Rust toolchain
    cargo
    rustc

    # System utilities
    binutils # Provides 'strip'
    glibc.static # Required for static linking (crt-static)
  ];

  # Set environment variables automatically when entering the shell
  env = {
    BUILD_VIRTME_NG_INIT = "1";
  };

  # 似乎这么搞了，连  uv tool install . 都不需要了
  shellHook = ''
    echo "Environment prepared for virtme-ng."
    echo "Python dependencies (argcomplete, requests) are now available."
    echo "You can run ./vng directly."
  '';
}
