# Generated by Qwen
$dotfiles = "$HOME\.dotfiles"
$localappdata = $env:LOCALAPPDATA
$appdata = $env:APPDATA

$links = @{
    "nvim" = "$appdata\nvim"
    "config\gitui" = "$appdata\gitui"
    "config\zellij" = "$appdata\Zellij\config"
}

$legacyZellij = "$appdata\zellij"
if (Test-Path $legacyZellij) {
    $legacyItem = Get-Item $legacyZellij -Force
    if ($legacyItem.LinkType -eq "Junction" -and $legacyItem.Target -eq "$dotfiles\config\zellij") {
        Remove-Item -Path $legacyZellij -Force
    }
}

# 构建软链接
foreach ($key in $links.Keys) {
    $source = "$dotfiles\$key"
    $target = $links[$key]

    if (Test-Path $source) {
        $targetParent = Split-Path -Parent $target
        if (!(Test-Path $targetParent)) {
            New-Item -ItemType Directory -Path $targetParent -Force | Out-Null
        }
        if (Test-Path $target) {
            Remove-Item -Recurse -Force $target
        }
        New-Item -ItemType Junction -Path $target -Target $source -Force
        Write-Host "✅ Linked $key"
    } else {
        Write-Warning "⚠️ Source not found: $source"
    }
}

# 复制文件
$files = @(
    @{ source = "$dotfiles\.gitconfig"; target = "$HOME\.gitconfig" }
    @{
      source = "$dotfiles\config\windows\pwsh.ps1";
      target = "$HOME\Documents\PowerShell\Microsoft.PowerShell_profile.ps1"
    }
    @{
      source = "$dotfiles\config\wezterm.lua";
      target = "$HOME\.config\wezterm\wezterm.lua"
    }
    @{
      source = "$dotfiles\config\tigrc.conf";
      target = "$HOME\.tigrc"
    }
    @{
      source = "$dotfiles\config\starship.toml";
      target = "$HOME\.config\starship.toml"
    }
)

foreach ($file in $files) {
    if (Test-Path $file.source) {
        Copy-Item -Path $file.source -Destination $file.target -Force
        Write-Host "✅ Copied $($file.source)"
    }
}

# TODO 为什么这个脚本 执行的这么慢啊
# https://learnxinyminutes.com/powershell/
