[[manager.prepend_keymap]]
on   = [ "<C-s>" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = [ "<C-n>" ]
run  = 'shell "nautilus --browser . && exit 0" --block --confirm'
desc = "Open shell here"
